### ISSUE TITLE
Node.js tutorial(s)

### ISSUE THREAD

**Issue by adrien-chaussabel** [adrien-chaussabel/CSC308-Club-Sports#15]
#8 
Run through one or more node.js tutorials.

Some examples:
https://www.codementor.io/@kakarganpat/how-to-setup-react-and-node-js-in-a-project-koxwqbssl
https://www.twilio.com/blog/react-app-with-node-js-server-proxy

**Comment by adrien-chaussabel** [comment]
Estimate = 2 hrs (each)

**Comment by caoimhegall** [comment]
Actual Time = 2hrs (each)
