### ISSUE TITLE
Make the login page fully functional

### ISSUE THREAD

**Issue by caoimhegall** [adrien-chaussabel/CSC308-Club-Sports#43]
#8
Connect the database to login page so users can login with registered username and password. Hash passwords and give error messages etc.

**Comment by caoimhegall** [comment]
Time Estimate = 6hrs

**Comment by adrien-chaussabel** [comment]
@caoimhegall

**Comment by adrien-chaussabel** [comment]
Actual time sprint 3:  7 hours
