### ISSUE TITLE
Look into Bootstrap to replace CSS pages

### ISSUE THREAD

**Issue by adrien-chaussabel** [adrien-chaussabel/CSC308-Club-Sports#47]
Do some research on Bootstrap and see how easily we can integrate into our current page without disrupting too much.

https://getbootstrap.com/

**Comment by caoimhegall** [comment]
Time Estimate = 2hrs each

**Comment by adrien-chaussabel** [comment]
Helped by @rbhalodi @samiur98 @LUARM

**Comment by adrien-chaussabel** [comment]
Actual time: 3 hours total
