### ISSUE TITLE
Connect Events Column to Database

### ISSUE THREAD

**Issue by adrien-chaussabel** [adrien-chaussabel/CSC308-Club-Sports#49]
Put the events table onto the cloud DB and then connect the events column to the table so that it prints back end data instead of fake backend (hardcoded) data.

**Comment by adrien-chaussabel** [comment]
Estimate: 5 hrs

**Comment by adrien-chaussabel** [comment]
Helped by @adrien-chaussabel

**Comment by samiur98** [comment]
Added functionality to events backend, actual time: 3hrs.

**Comment by adrien-chaussabel** [comment]
Actual time: 5 hours
