### ISSUE TITLE
Research how to connect sports pages

### ISSUE THREAD

**Issue by caoimhegall** [adrien-chaussabel/CSC308-Club-Sports#73]
Each page has similar elements, need to research how to connect each page to individual sports

**Comment by caoimhegall** [comment]
Helped by @samiur98

**Comment by caoimhegall** [comment]
Time Estimate = 3 hrs

**Comment by samiur98** [comment]
Backend for this issue completed, for time estimate check the separate issue that was created specific to the backend.
